Instructors/Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;

namespace Instructors.Controllers
{
    
    [Authorize]
    public class CourseController : Controller
    {
        // AppDbContext context;

        ICourseRepository CourseRepository;
        IDepartmentRepository DepartmentRepository;
        public CourseController(ICourseRepository _crsRepo , IDepartmentRepository _deptRepo)
        {
           // context = new AppDbContext();
            CourseRepository = _crsRepo;
            DepartmentRepository = _deptRepo;
        }   
        public IActionResult Index(int numberOfPage=0)
        {
            int TotalPages = (int)Math.Ceiling(CourseRepository.GetTotalCoursesCount() / 8.0);

            if(numberOfPage < 0) numberOfPage = 0;
            else if(numberOfPage>=TotalPages) numberOfPage = TotalPages-1;

            int NumberOfCoursesPerPage = 8;
            int PagesToSkip = numberOfPage* NumberOfCoursesPerPage;
            
            
            List<Course> courses = CourseRepository.GetAll(PagesToSkip, NumberOfCoursesPerPage);//context.Courses.ToList();
            ViewBag.CurrentPage = numberOfPage;
            ViewBag.TotalPages = TotalPages;


            return View("Index",courses);
        }
       
        public IActionResult Edit(int id)
        {
            Course? crs = CourseRepository.GetById(id);//context.Courses.Find(id);
            if (crs is null)
            {
                return View("index");
            }
            CourseCreateViewModel model = new CourseCreateViewModel();
            CopyDataFromModelToViewModel(crs, model);
            model.Departments = GetDepartments();
            return View("Edit",model);
        }

        [HttpPost]
        public IActionResult UpdateCourse(CourseCreateViewModel CrsFromView)
        {
            if (CrsFromView.Dept_id == 0)
            {
                ModelState.AddModelError("Dept_id", "Please Select Department");
            }
            else if (ModelState.IsValid)
            {
                Course? crs = CourseRepository.GetById(CrsFromView.Id);//context.Courses.Find(CrsFromView.Id);
                if (crs is null)
                {
                    return View("Index");
                }
                CopyDataFromViewModelToModel(CrsFromView, crs);
                CourseRepository.Update(crs); //context.Courses.Update(crs);
                CourseRepository.SaveChanges(); //context.SaveChanges();
                return RedirectToAction("Index");
            }
            CrsFromView.Departments = GetDepartments();
            return View("Edit", CrsFromView);
        }
        public IActionResult AddCourse()
        {
            CourseCreateViewModel model = new CourseCreateViewModel();
            model.Departments = GetDepartments();

            return View("AddCourse", model);

        }

        [HttpPost]
        public IActionResult SaveCourse(CourseCreateViewModel CrsFromView)
        {
            //if (CrsFromView.MinDegree >= CrsFromView.Degree)
            //{
            //    ModelState.AddModelError("MinDegree", "Min Degree Must Be Less Than Degree");
            //}
             if (CrsFromView.Dept_id == 0)
            {
                ModelState.AddModelError("Dept_id", "Please Select Department");
            }
            
            else if (ModelState.IsValid)
            {
                Course crs = new Course();
                CopyDataFromViewModelToModel(CrsFromView, crs);

                CourseRepository.Add(crs);// context.Courses.Add(crs);
                CourseRepository.SaveChanges(); // context.SaveChanges();
                return RedirectToAction("GetAll");
            }

            CrsFromView.Departments = GetDepartments();
            return View("AddCourse",CrsFromView);
            
        }


        public IActionResult TestMinDegreeLessThanDegree(float MinDegree, float Degree)
        {
            if (MinDegree >= Degree)
            {
                return Json($"Min Degree Must Be Less Than Degree");
            }
            return Json(true);
        }

        public IActionResult ShowCourseResult(int id,[FromServices]ICrsResultRepository crsResultRepository)
        {
            ShowCourseResultViewModel courseResultViewModel = new ShowCourseResultViewModel();
            Course? course = CourseRepository.GetById(id); //context.Courses.FirstOrDefault(x=>x.Id==id);
            if (course is null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                courseResultViewModel.Id = course.Id;
                courseResultViewModel.Name = course.Name;
                courseResultViewModel.Degree = course.Degree;
                courseResultViewModel.MinDegree = course.MinDegree;
                courseResultViewModel.Hours = course.Hours;
                courseResultViewModel.DepartmentName = DepartmentRepository.GetById(course.Dept_id)!.Name; //context.Departments.FirstOrDefault(x => x.ID == course.Dept_id)!.Name;
                List<CrsResult> results = crsResultRepository.GetCoureseResultWithTrainee(id); //context.CrsResults.Include(x=>x.Trainee).Where(x => x.Crs_id == id).ToList();

                //حساب نسبة كام في المية لكل طالب
                float MaxDegree = course.Degree;
                float MinDegree = (int)course.MinDegree;
               
                //float percent=results.

                courseResultViewModel.ShowResultViewModels = new List<ShowResultViewModel>();
                foreach (var result in results)
                {
                    float Degree = result.Degree;
                    float percent = (Degree / MaxDegree) * 100;
                    ShowResultViewModel resultViewModel = new ShowResultViewModel()
                    {
                        TraineeName = result.Trainee.Name,
                        Trainee_id = result.Trainee_id,
                        Crs_id = result.Crs_id,
                        DegreeStudent = result.Degree,
                        color = (result.Degree >= MinDegree) ? "Green" : "Red",
                        Result = (result.Degree >= MinDegree) ? $"{percent}%  Pass" : $"{percent}%  Fail"
                    };
                    courseResultViewModel.ShowResultViewModels.Add(resultViewModel);
                }
            }
                return View("ShowCourseResult", courseResultViewModel);
        }

        public IActionResult Delete(int id)
        {
            Course? course = CourseRepository.GetById(id);//context.Courses.Find(id);
            if (course is not null)
            {
                CourseRepository.Delete(id);//context.Courses.Remove(course);
                CourseRepository.SaveChanges();//context.SaveChanges();
            }
            return RedirectToAction("Index");

        }

        public IActionResult GetCoursesByDeptId(int deptId)
        {
            var courses = CourseRepository.GetCoursesByDeptId(deptId);
            return Json(courses);
        }


        //------------------- Private Methods ------------------//
        private void CopyDataFromViewModelToModel(CourseCreateViewModel source, Course destination)
        {
            destination.Id = source.Id;
            destination.Name = source.Name;
            destination.Degree = source.Degree is not null? (float)source.Degree : 0;
            destination.MinDegree = source.MinDegree is not null ? (float)source.MinDegree : 0;
            destination.Hours = source.Hours is not null ? (float)source.Hours : 0;
            destination.Dept_id = source.Dept_id;
        }
        private void CopyDataFromModelToViewModel(Course source, CourseCreateViewModel destination)
        {
            destination.Id = source.Id;
            destination.Name = source.Name;
            destination.Degree = source.Degree;
            destination.MinDegree = source.MinDegree;
            destination.Hours = source.Hours;
            destination.Dept_id = source.Dept_id;
        }
        private List<Department> GetDepartments()
        {
            return DepartmentRepository.GetAll();//context.Departments.ToList();
        }
        
    }
}

Instructors/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;

namespace Instructors.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository deptRepo;
        private readonly ICourseRepository crsRepo;

        public DepartmentController(IDepartmentRepository _deptRepo ,ICourseRepository _crsRepo)
        {
            deptRepo = _deptRepo;
            crsRepo = _crsRepo;
        }
        public IActionResult Index()
        {
            List<Department> departments = deptRepo.GetAll();
            DepartmentCreateViewModel deptViewModel = new();

            return View(( departments,deptViewModel));
        }
       
        [HttpPost]
        public IActionResult Add([FromBody] DepartmentCreateViewModel deptFromView)
        {
            if (ModelState.IsValid)
            {
                Department Dept = new Department
                {
                    Name = deptFromView.Name,
                    Manager = deptFromView.Manager
                };
                deptRepo.Add(Dept);
                deptRepo.SaveChanges();
                object dept = new { success = true, id = Dept.ID, name = Dept.Name, manager = Dept.Manager };
                return Json(dept);
            }
            return Json(new { success = false });
        }
         
        public IActionResult Delete(int id)
        {
            Department? dept = deptRepo.GetById(id);
          
            if (dept is null)
            {

                object obj = new
                {
                    title = "Error",
                    text = "this Department Not Exist",
                    icon = "warning"
                };
                return Json(obj);

            }
           
            bool testDelete=deptRepo.Delete(id);
            deptRepo.SaveChanges();
            if (testDelete)
            {
                object obj = new
                {
                    title = "Success",
                    text = $"The Department ({dept.Name}) is Deleted Successfuly ",
                    icon = "success"
                };
                return Json(obj);
            }
            object Fail = new
            {
                title = "Fail",
                text = $"This Department ({dept.Name}) Contain Trainee or Courses or Instructors ",
                icon = "error"
            };
            return Json(Fail);
        }
        public IActionResult Edit(int id)
        {
            Department? dept = deptRepo.GetById(id);
            if (dept is null) return RedirectToAction("Index");
            DepartmentCreateViewModel deptViewModel = new DepartmentCreateViewModel
            {
                ID = id,
                Name = dept.Name,
                Manager = dept.Manager
            };
            return View(deptViewModel);
        }
        [HttpPost]
        public IActionResult Edit(DepartmentCreateViewModel deptFromView)
        {
            if(ModelState.IsValid)
            {
                
                    Department dept = new Department
                    {
                        ID=deptFromView.ID,
                        Name = deptFromView.Name,
                        Manager = deptFromView.Manager
                    };
                    deptRepo.Update(dept);
                    deptRepo.SaveChanges();
                return RedirectToAction("Index");
                
            }
            return View(deptFromView);
        }
        public IActionResult Details(int id) 
        {
            Department? dept=deptRepo.GetById(id);
            if (dept is null) { return RedirectToAction("index"); }
            DepartmentCreateViewModel DeptViewModel = new()
            {
                ID=dept.ID ,
                Name=dept.Name,
                Manager=dept.Manager,
                Courses= crsRepo.GetCoursesByDeptId(dept.ID)

            };
            return View(DeptViewModel);
        }

    }
}

Instructors/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Instructors.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SaveRole(AddRoleViewModel roleViewModel)
        {
            if(ModelState.IsValid)
            {
                //save role in database
                IdentityResult resultSaveRole = await roleManager.CreateAsync(new IdentityRole { Name =roleViewModel.RoleName });
                if(resultSaveRole.Succeeded)
                {
                    return Content("Role Saved Successfully");
                }
                foreach(var error in resultSaveRole.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            return View("AddRole" , roleViewModel);
        }
    }
}

Instructors/Controllers/TraineeController.cs
using Instructors.Repository;
namespace Instructors.Controllers
{
    public class TraineeController : Controller
    {
        private readonly ITraineeRepository traineeRepo;
        private readonly ICrsResultRepository crsResultRepo;
        public TraineeController(ITraineeRepository _traineeRepo, ICrsResultRepository _crsResultRepo) 
        {
            traineeRepo = _traineeRepo;
            crsResultRepo = _crsResultRepo;
        }
        public IActionResult ShowResult(int id , int crsId)
        {
            if(id==0 || crsId==0)
            {
                return View("Index");
            }

            var Result=crsResultRepo.GetByIdAndCrsId(id, crsId);
            if (Result==null)
            {
                return View("Index");
            }
            var ResultStudentToView = new ShowResultViewModel()
            {
               TraineeName= Result?.Trainee.Name,
                CourseName= Result?.Course.Name,
                Trainee_id= id,
                Crs_id= crsId,
                DegreeStudent= Result?.Degree,
                color= (Result?.Degree >= Result?.Course.MinDegree) ? "Green" : "Red",
                Result= (Result?.Degree >= Result?.Course.MinDegree) ? "Pass" : "Fail"

            };

        
            return View("ShowResult",ResultStudentToView);
        }
        public IActionResult Add()
        {
            return View("Index");
        }
    }
}

Instructors/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Instructors</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Instructors.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Instructors</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Instructors - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Instructors/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - ITI</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <!-- Custom Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/css/LoginPage.css" rel="stylesheet" />
</head>
<body class=" d-flex flex-column h-100" style="background-image: url('@Url.Content("~/image/00.jpg")')">
    <main class="flex-shrink-0">
        <!-- Navigation-->
        <partial name="_navLayout" />
       
        <!-- Header-->
        <header class="py-5">
            <div class="container px-5 pb-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-xxl-5">
                        <!-- Header text content-->
                        <div class="text-center text-xxl-start">
@*                             <div class="badge bg-gradient-primary-to-secondary text-white mb-4"><div class="text-uppercase"> Trainee &middot; Department &middot; Course &middot; Instructor</div></div>
 *@                            @* <h1 class="display-3 fw-bolder mb-5"><span class="text-gradient d-inline">Get online and grow fast</span></h1> *@
                            @RenderBody()

                            
                            @* <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xxl-start mb-3">
                                <a class="btn btn-primary btn-lg px-5 py-3 me-sm-3 fs-6 fw-bolder" href="resume.html">Resume</a>
                                <a class="btn btn-outline-dark btn-lg px-5 py-3 fs-6 fw-bolder" href="projects.html">Projects</a>
                            </div> *@
                        </div>
                    </div>
                    
                </div>
            </div>
        </header>
        <!-- About Section-->
        <section class="bg-light py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-xxl-8">
                        <div class="text-center my-5">
                            <h2 class="display-5 fw-bolder"><span class="text-gradient d-inline">About The System</span></h2>
                            <p class="lead fw-light mb-4">This project is a complete system for managing students, instructors, and courses.</p>
                            <p class="text-muted">The system provides tools to register students, assign instructors, manage course details, track performance, and organize academic operations efficiently. It is designed to be simple, scalable, and easy to use for educational institutions.</p>
                            <div class="d-flex justify-content-center fs-2 gap-4">
                                <a class="text-gradient" href="#!"><i class="bi bi-twitter"></i></a>
                                <a class="text-gradient" href="#!"><i class="bi bi-linkedin"></i></a>
                                <a class="text-gradient" href="#!"><i class="bi bi-github"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        
    </main>
    <!-- Footer-->
    <footer class="bg-white py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0">Copyright &copy; Your Website 2026</div></div>
                <div class="col-auto">
                    <a class="small" href="#!">Privacy</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Terms</a>
                    <span class="mx-1">&middot;</span>
                    <a class="small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>

Instructors/Views/Shared/_navLayout.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
    <div class="container px-5">
        <a class="navbar-brand" href="index.html"><span class="fw-bolder text-primary">Dragon</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Home">Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Instructor">Instructors</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Course">Courses</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Department">Departments</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Trainee">Traineies</a></li>
                    if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item"><a class="nav-link" asp-action="AddRole" asp-controller="Role">Roles</a></li>
                    }
                    <li><a asp-action="Logout" asp-controller="Account" class="btn btn-danger">Signout</a></li>
                }
                else
                {
                    <li><a asp-action="Login" asp-controller="Account" class="btn btn-success">Login</a></li>
                    <span>  </span>
                    <li><a asp-action="Register" asp-controller="Account" class="btn btn-warning">Register</a></li>
                }
            </ul>
        </div>
    </div>
</nav>