Instructors/Models/Entities/Instructor.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Newtonsoft.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Instructors.Models
{
    public class Instructor
    {

        public int Id { get; set; }
        
        public string Name { get; set; }
        public string? Image { get; set; }

        public float Salary { get; set; }
        public string Address { get; set; }

        
        [ForeignKey("Department")]
        public int Dept_id { get; set; }

        [ForeignKey("Course")]
        public int Crs_id { get; set; }

        public Department Department { get; set; } = null!;
        public Course Course { get; set; } = null!;
    }
}

Instructors/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;

namespace Instructors.Controllers
{
    [HandleError]
    [Authorize]
    public class InstructorController : Controller
    {
        
        private readonly IInstructorRepository instRepo;
        private readonly IDepartmentRepository deptRepo;
        private readonly ICourseRepository crsRepo;

        public InstructorController(IInstructorRepository _InstRepo,IDepartmentRepository _deptRepo ,ICourseRepository _crsRepo)
        {
            instRepo = _InstRepo;
            deptRepo = _deptRepo;
            crsRepo = _crsRepo;
        }
        public IActionResult Index()
        {
            List<Instructor> instructors = instRepo.GetAll();
            return View("Index", instructors);
        }
        public IActionResult Details(int id)
        {
            Instructor? instructor = instRepo.GetByIdIncludeDeptAndCourse(id);
            return View("Details", instructor);
        }
        public IActionResult Edit(int id)
        {
            Instructor? ins = instRepo.GetById(id);
            if (ins is null) return View("index");
            InstructorCreateViewModel ICVM= GetInstructorCreateViewModel(null, ins);
            return View(ICVM);
        }
        [HttpPost]
        public IActionResult Edit(InstructorCreateViewModel InsFromView)
        {
            if (ModelState.IsValid)
            {
                if (InsFromView.Dept_id == 0)
                {
                    ModelState.AddModelError("Dept_id", "Please Select Department");
                }
                else if (InsFromView.Crs_id == 0)
                {
                    ModelState.AddModelError("Crs_id", "Please Select Course");
                }
                else
                {
                    Instructor ins = new Instructor()
                    {
                        Id = InsFromView.Id,
                        Name = InsFromView.Name,
                        Image = InsFromView.Image,
                        Salary = (InsFromView.Salary is null) ? 0 : (float)InsFromView.Salary,
                        Address = InsFromView.Address,
                        Dept_id = InsFromView.Dept_id,
                        Crs_id = InsFromView.Crs_id
                    };
                    instRepo.Update(ins);
                    instRepo.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            InsFromView = GetInstructorCreateViewModel(InsFromView, null);

            return View("Edit", InsFromView);
        }
        public IActionResult Delete(int id)
        {
            return PartialView("_DeleteView");
        }
      
        public IActionResult AddInstructor()
        {
            InstructorCreateViewModel ICVM = GetInstructorCreateViewModel(null,null);

            return View("AddInstructor" , ICVM);
        }
        [HttpPost]
        public IActionResult SaveInstructor(InstructorCreateViewModel InsFromView)
        {
            if (ModelState.IsValid)
            {
                if (InsFromView.Dept_id == 0)
                {
                    ModelState.AddModelError("Dept_id", "Please Select Department");
                }
                else if (InsFromView.Crs_id == 0)
                {
                    ModelState.AddModelError("Crs_id", "Please Select Course");
                }
                else
                {
                    Instructor ins = new Instructor()
                    {
                        
                        Name = InsFromView.Name,
                        Image = InsFromView.Image,
                        Salary = (InsFromView.Salary is null) ? 0 : (float)InsFromView.Salary,
                        Address = InsFromView.Address,
                        Dept_id = InsFromView.Dept_id,
                        Crs_id = InsFromView.Crs_id
                    };
                    instRepo.Add(ins);
                    instRepo.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            InsFromView=GetInstructorCreateViewModel(InsFromView,null);

            return View("AddInstructor",InsFromView);
        }
       
        
        private InstructorCreateViewModel GetInstructorCreateViewModel(InstructorCreateViewModel? insFromAction, Instructor? ins)
        {
            InstructorCreateViewModel ICVM;
            if (insFromAction == null) { ICVM = new(); }
            else { ICVM = insFromAction; }
            
            if (ins is not null)
            {
                ICVM.Id = ins.Id;
                ICVM.Name = ins.Name;
                ICVM.Image = ins.Image!;
                ICVM.Salary = ins.Salary;
                ICVM.Address = ins.Address;
                ICVM.Dept_id = ins.Dept_id;
                ICVM.Crs_id = ins.Crs_id;
            }

            List<Department> departments = deptRepo.GetAll();
            List<Course> courses = crsRepo.GetCoursesByDeptId(ICVM.Dept_id).ToList();
            ICVM.Courses = courses;
            ICVM.Departments = departments;
            return ICVM;
        }
    }
}

Instructors/Views/Instructor/AddInstructor.cshtml
@model InstructorCreateViewModel
@{
    ViewData["Title"] = "AddInstructor";
}

<link rel="stylesheet" href="~/css/AddOrEditForm.css" asp-append-version="true" />
<h1>AddInstructor</h1>
<form asp-action="SaveInstructor" asp-controller="Instructor" method="post" class="form form-control" 
      autocomplete="off" 
      autocorrect="off"
      autocapitalize="off"
      spellcheck="false">
    <partial name="_commonAddAndEditInstructor" />
</form>

<partial name="_getCrsByDeptIdUsingAjax" />


@* <script>
    // نحول Model.Courses إلى JSON في جافاسكريبت
    var allCourses = @Html.Raw(Json.Serialize(Model.Courses));

    $("#DepartmentId").change(function () {
        var deptId = $(this).val();
        $("#CourseId").empty();
        $("#CourseId").append('<option value="">-- Select Course --</option>');

        // نفلتر الكورسات حسب القسم
        var filtered = allCourses.filter(c => c.dept_id == deptId);
        filtered.forEach(course => {
            $("#CourseId").append('<option value="' + course.id + '">' + course.name + '</option>');
        });
    });
</script> *@

Instructors/Views/Instructor/Edit.cshtml
@model InstructorCreateViewModel
@{
    ViewData["Title"] = "Edit Course";
}
<link rel="stylesheet" href="~/css/AddOrEditForm.css" asp-append-version="true" />


<h1 class="display-3 fw-bolder mb-5"><span class="text-gradient d-inline">Edit Instructor</span></h1>
<form asp-action="Edit" asp-controller="Instructor" method="post" class="form form-control">
    <input hidden asp-for="Id" />
    <partial name="_commonAddAndEditInstructor" />
</form>
<partial name="_getCrsByDeptIdUsingAjax" />

Instructors/Views/Instructor/Index.cshtml
@model List<Instructor>;
@{
    ViewData["Title"] = "Index";
}
<h1 class="display-3 fw-bolder mb-5"><span class="text-gradient d-inline">Instructors</span></h1>


<a asp-action="AddInstructor" asp-controller="Instructor" class="btn btn-success">Add Instructor</a>
<table class="table table-primary table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Image</th>
            <th>Details</th>
            <th>Delete | Edit</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var instructor in Model)
        {
            <tr>
                <td>@instructor.Id</td>
                <td>@instructor.Name</td>
                <td>
                    @if(@instructor.Image != null){ <img src="~/image/@instructor.Image" alt="@instructor.Name" width="100" height="100" />}
                    else { <img src="~/image/0.jpg" alt="@instructor.Name" width="100" height="100" />}
                </td>
                <td>
                    <a asp-controller="Instructor" asp-action="Details" asp-route-id="@instructor.Id" class="btn btn-info">Details</a>
                </td>
                <td>
                    <a asp-controller="Instructor" asp-action="Edit" asp-route-id="@instructor.Id" class="btn btn-warning">Edit</a>
                    <a asp-controller="Instructor" asp-action="Delete" asp-route-id="@instructor.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

Instructors/Views/Instructor/_commonAddAndEditInstructor.cshtml
@model InstructorCreateViewModel;
<center>
    <label asp-for="Name" class="form-label">Name </label>
    <input asp-for="Name" class=" input-group-text" />
    <span asp-validation-for="Name" class="text-danger"></span> <br />

    <label asp-for="Salary" class="form-label"> Salary</label>
    <input asp-for="Salary" class="input-group-text" />
    <span asp-validation-for="Salary" class="text-danger"></span> <br />



    <label asp-for="Address" class="form-label">Address</label>
    <input asp-for="Address" class="input-group-text" />
    <span asp-validation-for="Address" class="text-danger"></span> <br />


    <label asp-for="Dept_id" class="form-label">Department Name</label>
    <select id="DepartmentId" asp-for="Dept_id" class="input-group-text" onchange="GetCourse()">
        @if (Model?.Departments == null || Model?.Departments.Count == 0)
        {
            <option disabled selected> No Departments Available </option>
        }
        else
        {

            <option value="0">-- Select Department --</option>
            @foreach (var dept in Model.Departments)
            {


                if (dept.ID == Model.Dept_id)
                {
                    <option value="@dept.ID" selected> @dept.Name </option>
                }
                else
                {
                    <option value="@dept.ID"> @dept.Name </option>
                }
            }
        }
    </select>
    <span asp-validation-for="Dept_id" class="text-danger"></span> <br />


    <label asp-for="Crs_id" class="form-label">Coure Name</label>
    <select id="CourseId" asp-for="Crs_id" class="input-group-text">
        @if (Model?.Courses == null || Model?.Courses.Count == 0)
        {
            <option disabled selected> No Courses Available </option>
        }
        else
        {

            <option value="0">-- Select Course --</option>
            @foreach (var Crs in Model.Courses)
            {


                if (Crs.Id == Model.Crs_id)
                {
                    <option value="@Crs.Id" selected> @Crs.Name </option>
                }
                else
                {
                    <option value="@Crs.Id"> @Crs.Name </option>
                }
            }
        }
    </select>
    <span asp-validation-for="Crs_id" class="text-danger"></span> <br />


    <button type="submit" class="btn btn-primary mt-3"> Save Instructor </button>

    <div asp-validation-summary="All" class="list-group-item-danger"></div>
</center>

Instructors/Views/Instructor/_getCrsByDeptIdUsingAjax.cshtml
<script>
    function GetCourse()
    {
        var DeptId=document.getElementById("DepartmentId").value;
        var CourseId=document.getElementById("CourseId");
        CourseId.innerHTML=`<option value="${0}"> -- Select Course -- </option>`;
        $.ajax({url: "/Course/GetCoursesByDeptId?deptid="+DeptId, success: function(courses){
        //console.log(result)
        for(let c of courses ){
            CourseId.innerHTML+=`<option value="${c.id}"> ${c.name} </option>`
        }
        }});
        // console.log(DeptId);
    }
</script>